### ISSUE TITLE
Expose endpoints walrus provides

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#1]
I'm trying to use `muse` from `us` as mentioned at https://github.com/lukechampine/walrus/issues/13#issuecomment-650203210 but it looks like it doesn't expose any endpoints that walrus provides. 

Could you expose endpoints walrus provides as same as endpoints shard provides so that `walrus.Client` can access it?

**Comment by lukechampine** [comment]
To access the `walrus` API, you should create a separate client: `walrus.NewClient(walrusAddr)`.

**Comment by jkawamoto** [comment]
The `walrusAddr` is randomly generated here

https://github.com/lukechampine/muse/blob/0906d74036b2b8a12c717d2abdc641a541bc4c8e/cmd/muse/main.go#L169-L171

and it's not easy to access from other applications. 

If exposing walrus API is difficult, we need to change L169 to

```go
l, err := net.Listen("tcp", "localhost:9380") 
```

**Comment by lukechampine** [comment]
ah, you're right. I will add a flag to allow specifying the `walrus` server address manually. I'll also print out the address that the `walrus` server is listening on.

**Comment by lukechampine** [comment]
Fixed in https://github.com/lukechampine/muse/commit/ab8dc90b81a20cc789a5846688b78f5d69ab6bbb

**Comment by lukechampine** [comment]
Oops, I closed this when I added the print statements, but I haven't added the flags yet. I'm not sure what the right API is, given that there are already `-w` and `-s` flags for specifying the addresses of *existing* `walrus`/`shard` servers. Maybe add `-wl` and `-sl` flags (`l` for "listen"), and return an error if specifying both `-w` and `-wl`?

**Comment by jkawamoto** [comment]
Thanks. But, I'm afraid that printing addresses don't work for Kubernetes because they should be fixed before staring servers. I opened an issue for the option flags: https://github.com/lukechampine/muse/issues/2.

I think we only need to specify an address for Walrus because muse proxies Shard server and we don't need to know the actual address of it.
