### ISSUE TITLE
communication error: rejected for including too few transaction fees

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#12]
We've been getting this error since two days ago, and no contract formation succeeds.

![2020-09-17](https://user-images.githubusercontent.com/1793096/93533238-7cfd7600-f910-11ea-9b0c-d775dcca6e29.png)

That's strange because the last muse update was one week ago, though.

**Comment by MeijeSibbel** [comment]
![image](https://user-images.githubusercontent.com/11735738/93537367-966fe380-f94b-11ea-876c-774748308fff.png)
It looks like transaction fees are spiking.

**Comment by jkawamoto** [comment]
I think there is another fee miscalculation like https://github.com/lukechampine/walrus-cli/issues/16 because the error has gone after defragging outputs.

**Comment by MeijeSibbel** [comment]
@jkawamoto it still occurs?

**Comment by jkawamoto** [comment]
Frequently defragging outputs is a workaround but I think it doesn't solve this problem.
