### ISSUE TITLE
FormContract: ReadResponse: consensus conflict: provided transaction set is invalid: invalid signature

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#15]
After the hard fork, it looks like no contract formation has succeeded.

**Comment by lukechampine** [comment]
This is because the host is on the other side of the fork. Either the host is running old code and you're running new code, or vice versa. `us` should produce correct signatures as of `v0.19.1`, and ditto for `walrus` as of `v0.10.4`.

**Comment by jkawamoto** [comment]
I thought https://github.com/lukechampine/walrus/issues/17 causes this error.
However, we still get this for example with this host [`ed25519:df1c4dc837c075e1e24d62effcf0a980842b91d036374750b36d7d8248310339`](https://siastats.info/hosts?=2353), which uses v1.5.4.

We're using muse v0.6.5 with https://github.com/lukechampine/shard/commit/d271a1d63374e82dc87ea893a21c9978d3583d90 (and `consensus.db` was resynced). We should be on the forked chain.

**Comment by jkawamoto** [comment]
Contract renewal looks like it doesn't work, and we get this error `RenewContract: ReadResponse: consensus conflict: provided transaction set is invalid: invalid signature`.

**Comment by lukechampine** [comment]
Hmm. Ok. Looks like there's one place where `walrus` still uses `ASICHardforkHeight` rather than `FoundationHardforkHeight`. :/
I'll fix that and then push new versions.

**Comment by jkawamoto** [comment]
Thanks. It looks like both contract formation and renewal work now! I'll close this issue.
