### ISSUE TITLE
Could not initialize server:parse "0.0.0.0:9480": first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#3]
I think the problem is that `shardAddr` is expected to be in `host:port` as this flag definition:

```
shardAddr := flag.String("s", "localhost:9580", "host:port of the shard server")
```

but it tries to parse the address as a URL:

https://github.com/lukechampine/muse/blob/91294ab90ff38c4ca7ae5bd03fd77fd0963dcd18/server.go#L374

**Comment by lukechampine** [comment]
Fixed in https://github.com/lukechampine/muse/commit/e8dd7bc0fa543e3ffc36be259424c3a2cfd67f1d.

This gave me an idea for the CLI flags:

```bash
$ muse -w localhost:9580          # starts a walrus server on localhost:9580
$ muse -w http://localhost:9580   # connects to an existing walrus server running at localhost:9580
```

That might be too subtle, though.
