### ISSUE TITLE
Get "https://muse:9480/synced": http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#4]
I think this should use `http` instead of `https`
https://github.com/lukechampine/muse/blob/e8dd7bc0fa543e3ffc36be259424c3a2cfd67f1d/server.go#L375

because shard uses `ListenAndServe` instead of `ListenAndServeTLS`: https://github.com/lukechampine/shard/blob/55ee50ba70b592ae3fa5d82a73bfa413f6c30b0f/cmd/shard/main.go#L51.

**Comment by lukechampine** [comment]
For security reasons, HTTPS is the default. You should be able to specify `http://` explicitly to make this work. However, as mentioned in https://github.com/lukechampine/shard/issues/3, I may remove the HTTPS default if Go's http client handles the redirect automatically.

**Comment by jkawamoto** [comment]
Regardless of which should be default in HTTP and HTTPS, I'm afraid that it won't work because of the reverse proxy.

I referred to a wong point in the first comment but muse starts shard as an HTTP server:

https://github.com/lukechampine/muse/blob/e8dd7bc0fa543e3ffc36be259424c3a2cfd67f1d/cmd/muse/main.go#L135

However, it sets up a reverse proxy assuming the backend serves HTTPS:

https://github.com/lukechampine/muse/blob/e8dd7bc0fa543e3ffc36be259424c3a2cfd67f1d/server.go#L381-L385

where `shardURL.Scheme` is "https" since `shardAddr = "https://" + shardAddr`.

Btw, I think if the backend serves HTTPS, the reverse proxy needs to the cert file of the host, doesn't it?

**Comment by lukechampine** [comment]
It will *default* to HTTPS, but if `shardAddr` already starts with `http://`, it won't modify it.

I've changed `muse` to add an explicit `http://` prefix to the address it's serving `shard`/`walrus` on: https://github.com/lukechampine/muse/commit/13685c9d478fff5f38595b62bfc6ed6f23818ba7. This should resolve the issue.
Given that Go seems to handle the HTTPS redirect automatically, I've also removed the default HTTPS behavior from the muse client, and I'll push changes to the `shard` and `walrus` clients that do the same.

**Comment by jkawamoto** [comment]
Thanks. 

I think you should check if the reverse proxy would work in the case where the backend `shard` server uses a self-signed certificate. Perhaps, you assume the shard server is provided as a public service. But, I think in most cases, it's provided as a private service and it might use a self-signed certificate to serve HTTPS.
