### ISSUE TITLE
Update us lib

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#5]
I think we need this PR https://github.com/lukechampine/us/pull/119 to fix https://github.com/lukechampine/us/issues/112.

**Comment by lukechampine** [comment]
done

**Comment by jkawamoto** [comment]
Could you re-update us lib so that muse import https://github.com/lukechampine/us/pull/120 and https://github.com/lukechampine/us/pull/121?

**Comment by lukechampine** [comment]
sure: https://github.com/lukechampine/muse/releases/tag/v0.5.9

**Comment by jkawamoto** [comment]
Thanks!
