### ISSUE TITLE
Read a request body after closing it

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/muse#7]
Perhaps, it won't affect anything but those two lines should be in reverse order:
https://github.com/lukechampine/muse/blob/9b684d1eb64e35196d2241a316c5e1fb1903e3fa/client.go#L40-L41

**Comment by lukechampine** [comment]
good catch!

**Comment by jkawamoto** [comment]
Fixed with b71d3153bd94eb68622be6de3253cb4403026dbb. Thanks!
